-- ==============================================================================
-- Migración 032: Ensayo 3 SIMCE Matemática 6° Básico (Catálogo Global & Preguntas)
-- Fecha: 2026-08-25
-- ==============================================================================

BEGIN;

-- 1. Registrar Evaluación en public.evaluaciones (Catálogo)
INSERT INTO public.evaluaciones (
  id,
  titulo,
  descripcion,
  asignatura_id,
  nivel,
  tiempo_limite,
  es_catalogo,
  precio_clp,
  descripcion_catalogo,
  profesor_id,
  created_at,
  updated_at
) VALUES (
  'eval-simce-mat-6b-e3',
  'Ensayo 3 SIMCE Matemática 6° Básico',
  'Evaluación oficial de Matemática para 6° Básico que mide Números y Operaciones, Patrones y Álgebra, Geometría, Medición y Datos y Probabilidades.',
  'asig-1',
  '6° Básico',
  90,
  TRUE,
  0,
  'Evaluación integral estándar SIMCE de Matemática 6° Básico con 35 ítems de selección múltiple, tabla de especificaciones MINEDUC y distribución psicométrica equilibrada.',
  NULL,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  descripcion = EXCLUDED.descripcion,
  asignatura_id = EXCLUDED.asignatura_id,
  nivel = EXCLUDED.nivel,
  tiempo_limite = EXCLUDED.tiempo_limite,
  es_catalogo = EXCLUDED.es_catalogo,
  descripcion_catalogo = EXCLUDED.descripcion_catalogo,
  updated_at = NOW();

-- 2. Insertar Preguntas en public.preguntas
INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-01',
  'eval-simce-mat-6b-e3',
  1,
  'asig-1',
  'eje-mat-1',
  'hab-mat-2',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  NULL,
  '¿Qué valor representa el dígito **3** en el número **5 237 491**?',
  '[{"letra": "A", "texto": "3", "es_correcta": false}, {"letra": "B", "texto": "30", "es_correcta": false}, {"letra": "C", "texto": "30 000", "es_correcta": true}, {"letra": "D", "texto": "3 000 000", "es_correcta": false}]'::jsonb,
  'C',
  'El dígito 3 se ubica en la posición de las decenas de mil (DM), por lo que su valor posicional es 3 × 10 000 = 30 000.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-02',
  'eval-simce-mat-6b-e3',
  2,
  'asig-1',
  'eje-mat-1',
  'hab-mat-2',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  NULL,
  '¿Qué valor representa el dígito **6** en el número **5 726 378**?',
  '[{"letra": "A", "texto": "6", "es_correcta": false}, {"letra": "B", "texto": "6 000", "es_correcta": true}, {"letra": "C", "texto": "60 000", "es_correcta": false}, {"letra": "D", "texto": "600 000", "es_correcta": false}]'::jsonb,
  'B',
  'El dígito 6 se encuentra en la posición de las unidades de mil (UM), por lo tanto su valor posicional es 6 × 1 000 = 6 000.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-03',
  'eval-simce-mat-6b-e3',
  3,
  'asig-1',
  'eje-mat-1',
  'hab-mat-3',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  NULL,
  'Observa la cantidad de habitantes de algunas ciudades de Chile:

| Ciudad | Cantidad de habitantes |
| :--- | :---: |
| Calama | 147 886 |
| Talca | 201 797 |
| Osorno | 145 475 |
| Puerto Montt | 218 858 |

¿Cuál de estas ciudades es la que tiene mayor cantidad de habitantes?',
  '[{"letra": "A", "texto": "Calama", "es_correcta": false}, {"letra": "B", "texto": "Talca", "es_correcta": false}, {"letra": "C", "texto": "Osorno", "es_correcta": false}, {"letra": "D", "texto": "Puerto Montt", "es_correcta": true}]'::jsonb,
  'D',
  'Al comparar las cantidades: 218 858 (Puerto Montt) > 201 797 (Talca) > 147 886 (Calama) > 145 475 (Osorno). La ciudad con mayor población es Puerto Montt.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-04',
  'eval-simce-mat-6b-e3',
  4,
  'asig-1',
  'eje-mat-1',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  '¿Cuál es el resultado de la siguiente operación combinada?

$$3 \cdot 8 - 6 : 2$$',
  '[{"letra": "A", "texto": "3", "es_correcta": false}, {"letra": "B", "texto": "9", "es_correcta": false}, {"letra": "C", "texto": "15", "es_correcta": false}, {"letra": "D", "texto": "21", "es_correcta": true}]'::jsonb,
  'D',
  'Siguiendo la jerarquía de operaciones: primero multiplicación y división de izquierda a derecha: (3 · 8) = 24 y (6 : 2) = 3. Luego la sustracción: 24 - 3 = 21.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-05',
  'eval-simce-mat-6b-e3',
  5,
  'asig-1',
  'eje-mat-1',
  'hab-mat-2',
  'seleccion_multiple',
  '6° Básico',
  'media',
  '/preguntas/simce_mat_6b_e3/p05_recta_numerica.png',
  'Observa la recta numérica:

¿Cuál es el número mixto que se encuentra en el punto **P** de la recta numérica?',
  '[{"letra": "A", "texto": "1 3/5", "es_correcta": true}, {"letra": "B", "texto": "1 4/5", "es_correcta": false}, {"letra": "C", "texto": "1 3/6", "es_correcta": false}, {"letra": "D", "texto": "1 4/6", "es_correcta": false}]'::jsonb,
  'A',
  'Entre el 1 y el 2 el tramo está dividido en 5 segmentos iguales (quintos). El punto P se ubica en la tercera marca después del 1, por lo que corresponde a 1 3/5.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-06',
  'eval-simce-mat-6b-e3',
  6,
  'asig-1',
  'eje-mat-1',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  'María y Pedro están compartiendo una pizza. María ha comido $\frac{5}{6}$ de la pizza y Pedro ha comido $\frac{1}{3}$. ¿Cuánto más ha comido María que Pedro?',
  '[{"letra": "A", "texto": "1/6", "es_correcta": false}, {"letra": "B", "texto": "4/3", "es_correcta": false}, {"letra": "C", "texto": "2/6", "es_correcta": false}, {"letra": "D", "texto": "1/2", "es_correcta": true}]'::jsonb,
  'D',
  'Restamos 5/6 - 1/3 = 5/6 - 2/6 = 3/6. Simplificando por 3 obtenemos 1/2.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-07',
  'eval-simce-mat-6b-e3',
  7,
  'asig-1',
  'eje-mat-1',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  NULL,
  'En una panadería, se usaron **2,75 kg** de harina el día lunes y **1,85 kg** de harina el día martes. ¿Cuántos kilogramos más de harina se usaron el día lunes?',
  '[{"letra": "A", "texto": "0,90 kg", "es_correcta": true}, {"letra": "B", "texto": "0,95 kg", "es_correcta": false}, {"letra": "C", "texto": "1,10 kg", "es_correcta": false}, {"letra": "D", "texto": "4,60 kg", "es_correcta": false}]'::jsonb,
  'A',
  'Calculamos la diferencia: 2,75 kg - 1,85 kg = 0,90 kg.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-08',
  'eval-simce-mat-6b-e3',
  8,
  'asig-1',
  'eje-mat-1',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  'En el 6° B de la escuela Los Alerces, se hizo una encuesta para decidir el color de las camisetas del equipo. Si de un total de **50** estudiantes, **30** prefirieron rojo y el resto azul, ¿cuál es la razón entre los que prefirieron azul y el total?',
  '[{"letra": "A", "texto": "1 : 2", "es_correcta": false}, {"letra": "B", "texto": "2 : 5", "es_correcta": true}, {"letra": "C", "texto": "3 : 5", "es_correcta": false}, {"letra": "D", "texto": "4 : 5", "es_correcta": false}]'::jsonb,
  'B',
  'Estudiantes que prefirieron azul: 50 - 30 = 20. La razón entre azul y el total es 20 : 50 = 2 : 5.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-09',
  'eval-simce-mat-6b-e3',
  9,
  'asig-1',
  'eje-mat-1',
  'hab-mat-2',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  NULL,
  '¿Qué número mixto es equivalente a la fracción impropia $\frac{7}{3}$?',
  '[{"letra": "A", "texto": "2 1/3", "es_correcta": true}, {"letra": "B", "texto": "3 1/7", "es_correcta": false}, {"letra": "C", "texto": "1 4/3", "es_correcta": false}, {"letra": "D", "texto": "2 2/3", "es_correcta": false}]'::jsonb,
  'A',
  'Al dividir 7 por 3 se obtiene cociente 2 y resto 1, lo que equivale a 2 enteros y 1/3 (2 1/3).',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-10',
  'eval-simce-mat-6b-e3',
  10,
  'asig-1',
  'eje-mat-1',
  'hab-mat-2',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  '/preguntas/simce_mat_6b_e3/p10_circulo_porcentajes.png',
  'El siguiente círculo está dividido en **10** partes iguales:

¿Qué porcentaje de la superficie total representa el sector ennegrecido?',
  '[{"letra": "A", "texto": "10%", "es_correcta": false}, {"letra": "B", "texto": "20%", "es_correcta": false}, {"letra": "C", "texto": "40%", "es_correcta": true}, {"letra": "D", "texto": "50%", "es_correcta": false}]'::jsonb,
  'C',
  'Hay 4 sectores sombreados de un total de 10. La fracción es 4/10 = 40/100 = 40%.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-11',
  'eval-simce-mat-6b-e3',
  11,
  'asig-1',
  'eje-mat-1',
  'hab-mat-2',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  NULL,
  'Observa la siguiente descomposición aditiva:

$$3\text{ UMi} + 4\text{ CM} + 5\text{ DM} + 6\text{ UM} + 7\text{ C} + 8\text{ D} + 9\text{ U}$$

¿Cuál es el número correspondiente?',
  '[{"letra": "A", "texto": "345 689", "es_correcta": false}, {"letra": "B", "texto": "3 456 789", "es_correcta": true}, {"letra": "C", "texto": "34 567 890", "es_correcta": false}, {"letra": "D", "texto": "3 004 567 809", "es_correcta": false}]'::jsonb,
  'B',
  '3 000 000 + 400 000 + 50 000 + 6 000 + 700 + 80 + 9 = 3 456 789.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-12',
  'eval-simce-mat-6b-e3',
  12,
  'asig-1',
  'eje-mat-1',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  '¿Cuál es el resultado de la siguiente suma de fracciones?

$$\frac{3}{4} + \frac{2}{3}$$',
  '[{"letra": "A", "texto": "5/7", "es_correcta": false}, {"letra": "B", "texto": "5/12", "es_correcta": false}, {"letra": "C", "texto": "6/12", "es_correcta": false}, {"letra": "D", "texto": "17/12", "es_correcta": true}]'::jsonb,
  'D',
  'Mínimo común múltiplo entre 4 y 3 es 12. Amplificando: 9/12 + 8/12 = 17/12.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-13',
  'eval-simce-mat-6b-e3',
  13,
  'asig-1',
  'eje-mat-1',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  '¿Cuál es el resultado de la expresión?

$$52 - 12 : 4 + 6 \cdot 3$$',
  '[{"letra": "A", "texto": "12", "es_correcta": false}, {"letra": "B", "texto": "31", "es_correcta": false}, {"letra": "C", "texto": "48", "es_correcta": false}, {"letra": "D", "texto": "67", "es_correcta": true}]'::jsonb,
  'D',
  'Primero resolvemos divisiones y multiplicaciones: 12 : 4 = 3 y 6 · 3 = 18. Luego de izquierda a derecha: 52 - 3 + 18 = 49 + 18 = 67.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-14',
  'eval-simce-mat-6b-e3',
  14,
  'asig-1',
  'eje-mat-1',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  NULL,
  '¿Cuál es el resultado de la multiplicación?

$$0,6 \cdot 100$$',
  '[{"letra": "A", "texto": "0,06", "es_correcta": false}, {"letra": "B", "texto": "0,600", "es_correcta": false}, {"letra": "C", "texto": "60", "es_correcta": true}, {"letra": "D", "texto": "600", "es_correcta": false}]'::jsonb,
  'C',
  'Al multiplicar un número decimal por 100, se desplaza la coma decimal dos lugares hacia la derecha: 0,6 × 100 = 60.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-15',
  'eval-simce-mat-6b-e3',
  15,
  'asig-1',
  'eje-mat-1',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  'Fernanda necesita comprar algunos materiales para el colegio. Si compra un pack de cartulinas por **$1 200**, dos lápices de **$450** cada uno y una tijera de **$600**, ¿cuál de las siguientes expresiones representa el vuelto o cambio que recibe al pagar con un billete de **$5 000**?',
  '[{"letra": "A", "texto": "5 000 − 1 200 + 450 + 600", "es_correcta": false}, {"letra": "B", "texto": "5 000 − (1 200 + 450 + 600)", "es_correcta": false}, {"letra": "C", "texto": "5 000 − 1 200 + 450 · 2 + 600", "es_correcta": false}, {"letra": "D", "texto": "5 000 − (1 200 + 450 · 2 + 600)", "es_correcta": true}]'::jsonb,
  'D',
  'El gasto total es la suma del pack de cartulinas (1 200), dos lápices (450 · 2) y la tijera (600). Al restar este total agrupado entre paréntesis a los $5 000 se obtiene: 5 000 − (1 200 + 450 · 2 + 600).',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-16',
  'eval-simce-mat-6b-e3',
  16,
  'asig-1',
  'eje-mat-1',
  'hab-mat-2',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  NULL,
  '¿Cuál de los siguientes números es **compuesto**?',
  '[{"letra": "A", "texto": "7", "es_correcta": false}, {"letra": "B", "texto": "11", "es_correcta": false}, {"letra": "C", "texto": "21", "es_correcta": true}, {"letra": "D", "texto": "23", "es_correcta": false}]'::jsonb,
  'C',
  '21 tiene como divisores a 1, 3, 7 y 21 (más de dos divisores), por lo que es un número compuesto. Los números 7, 11 y 23 son primos.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-17',
  'eval-simce-mat-6b-e3',
  17,
  'asig-1',
  'eje-mat-2',
  'hab-mat-4',
  'seleccion_multiple',
  '6° Básico',
  'media',
  '/preguntas/simce_mat_6b_e3/p17_secuencia_figuras.png',
  'La siguiente secuencia de figuras fue construida siguiendo una regla de formación:

¿Cuántos círculos habrá en la **figura 5**?',
  '[{"letra": "A", "texto": "8 círculos", "es_correcta": false}, {"letra": "B", "texto": "10 círculos", "es_correcta": true}, {"letra": "C", "texto": "16 círculos", "es_correcta": false}, {"letra": "D", "texto": "30 círculos", "es_correcta": false}]'::jsonb,
  'B',
  'Figura 1: 2 círculos; Figura 2: 4 círculos; Figura 3: 6 círculos; Figura 4: 8 círculos. La regla es multiplicar el número de figura por 2 ($2n$). Por ende, en la figura 5 habrá 5 × 2 = 10 círculos.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-18',
  'eval-simce-mat-6b-e3',
  18,
  'asig-1',
  'eje-mat-2',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  '/preguntas/simce_mat_6b_e3/p18_balanza_equilibrio.png',
  'Observa la siguiente balanza en equilibrio:

¿Cuál es el valor de $x$ en el platillo?',
  '[{"letra": "A", "texto": "6", "es_correcta": false}, {"letra": "B", "texto": "10", "es_correcta": false}, {"letra": "C", "texto": "11", "es_correcta": true}, {"letra": "D", "texto": "16", "es_correcta": false}]'::jsonb,
  'C',
  'La balanza representa la ecuación x + 5 = 16. Restando 5 a ambos lados obtenemos x = 16 - 5 = 11.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-19',
  'eval-simce-mat-6b-e3',
  19,
  'asig-1',
  'eje-mat-2',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  'Si el doble de un número es **34**, ¿cuál es el consecutivo de ese número?',
  '[{"letra": "A", "texto": "18", "es_correcta": true}, {"letra": "B", "texto": "35", "es_correcta": false}, {"letra": "C", "texto": "68", "es_correcta": false}, {"letra": "D", "texto": "69", "es_correcta": false}]'::jsonb,
  'A',
  'El doble de un número es 34: $2n = 34 \implies n = 17$. El número consecutivo (siguiente) a 17 es 17 + 1 = 18.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-20',
  'eval-simce-mat-6b-e3',
  20,
  'asig-1',
  'eje-mat-2',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  'Considera la ecuación:

$$x + 4 = 10$$

¿Cuál es el resultado de la expresión $x + 2$?',
  '[{"letra": "A", "texto": "6", "es_correcta": false}, {"letra": "B", "texto": "8", "es_correcta": true}, {"letra": "C", "texto": "14", "es_correcta": false}, {"letra": "D", "texto": "16", "es_correcta": false}]'::jsonb,
  'B',
  'De la ecuación $x + 4 = 10$, despejamos $x = 10 - 4 = 6$. Evaluando la expresión pedida: $x + 2 = 6 + 2 = 8$.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-21',
  'eval-simce-mat-6b-e3',
  21,
  'asig-1',
  'eje-mat-2',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  'Dada la ecuación algebraica:

$$3x + 6 = 21$$

¿Cuál es el valor de $x$?',
  '[{"letra": "A", "texto": "5", "es_correcta": true}, {"letra": "B", "texto": "9", "es_correcta": false}, {"letra": "C", "texto": "45", "es_correcta": false}, {"letra": "D", "texto": "81", "es_correcta": false}]'::jsonb,
  'A',
  'Restamos 6 a ambos lados: $3x = 21 - 6 = 15$. Dividimos por 3: $x = 15 / 3 = 5$.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-22',
  'eval-simce-mat-6b-e3',
  22,
  'asig-1',
  'eje-mat-2',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  'En un terreno rectangular, la diferencia entre el doble del largo y la medida del ancho es exactamente **15 metros**. Si el ancho mide **5 metros**, ¿cuántos metros de largo tiene el terreno?',
  '[{"letra": "A", "texto": "5", "es_correcta": false}, {"letra": "B", "texto": "10", "es_correcta": true}, {"letra": "C", "texto": "20", "es_correcta": false}, {"letra": "D", "texto": "40", "es_correcta": false}]'::jsonb,
  'B',
  'Planteamos la ecuación: $2L - 5 = 15 \implies 2L = 20 \implies L = 10\text{ metros}$.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-23',
  'eval-simce-mat-6b-e3',
  23,
  'asig-1',
  'eje-mat-2',
  'hab-mat-4',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  'Una tienda de libros obtiene una ganancia de **$3 500** por cada libro vendido. Si $y$ representa la cantidad de libros vendidos, ¿cuál de las siguientes expresiones representa la condición de que la ganancia sea, al menos, de **$70 000**?',
  '[{"letra": "A", "texto": "3 500 ≥ 70 000y", "es_correcta": false}, {"letra": "B", "texto": "3 500y ≥ 70 000", "es_correcta": true}, {"letra": "C", "texto": "3 500 + y ≥ 70 000", "es_correcta": false}, {"letra": "D", "texto": "70 000 + y ≥ 3 500", "es_correcta": false}]'::jsonb,
  'B',
  'La ganancia total por vender $y$ libros es $3\,500 \cdot y$. Que sea ''al menos $70\,000$'' significa mayor o igual (≥): $3\,500y \ge 70\,000$.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-24',
  'eval-simce-mat-6b-e3',
  24,
  'asig-1',
  'eje-mat-3',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  '/preguntas/simce_mat_6b_e3/p24_triangulo_cuadricula.png',
  'Observa el triángulo dibujado en la cuadrícula formada por cuadrados de $1\text{ cm}^2$:

¿Cuál es el área del triángulo?',
  '[{"letra": "A", "texto": "11 cm²", "es_correcta": false}, {"letra": "B", "texto": "12 cm²", "es_correcta": true}, {"letra": "C", "texto": "13 cm²", "es_correcta": false}, {"letra": "D", "texto": "16 cm²", "es_correcta": false}]'::jsonb,
  'B',
  'La base del triángulo mide 6 unidades (cm) y la altura relativa mide 4 unidades (cm). Área = (base × altura) / 2 = (6 × 4) / 2 = 24 / 2 = 12 cm².',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-25',
  'eval-simce-mat-6b-e3',
  25,
  'asig-1',
  'eje-mat-3',
  'hab-mat-2',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  '/preguntas/simce_mat_6b_e3/p25_plano_cartesiano.png',
  'Observa el rectángulo ABCD en el siguiente plano cartesiano:

¿En qué coordenadas se encuentra ubicado el **vértice C**?',
  '[{"letra": "A", "texto": "(2, 3)", "es_correcta": false}, {"letra": "B", "texto": "(3, 2)", "es_correcta": false}, {"letra": "C", "texto": "(3, 6)", "es_correcta": false}, {"letra": "D", "texto": "(6, 3)", "es_correcta": true}]'::jsonb,
  'D',
  'Proyectando el vértice C en el eje horizontal X se ubica en 6, y en el eje vertical Y en 3. Por ende, las coordenadas son (6, 3).',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-26',
  'eval-simce-mat-6b-e3',
  26,
  'asig-1',
  'eje-mat-3',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  '¿En qué cubo las caras sombreadas de color gris son **paralelas**?

| Opción A | Opción B |
| :---: | :---: |
| ![Cubo A](/preguntas/simce_mat_6b_e3/p26_cubo_a.png) | ![Cubo B](/preguntas/simce_mat_6b_e3/p26_cubo_b.png) |
| **Opción C** | **Opción D** |
| ![Cubo C](/preguntas/simce_mat_6b_e3/p26_cubo_c.png) | ![Cubo D](/preguntas/simce_mat_6b_e3/p26_cubo_d.png) |',
  '[{"letra": "A", "texto": "Cubo A", "es_correcta": false}, {"letra": "B", "texto": "Cubo B", "es_correcta": true}, {"letra": "C", "texto": "Cubo C", "es_correcta": false}, {"letra": "D", "texto": "Cubo D", "es_correcta": false}]'::jsonb,
  'B',
  'En el Cubo B las caras sombreadas corresponden a caras opuestas del cubo, las cuales son exactamente paralelas entre sí.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-27',
  'eval-simce-mat-6b-e3',
  27,
  'asig-1',
  'eje-mat-3',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  NULL,
  '¿En cuál de las siguientes cuadrículas hay un **triángulo rectángulo**?

| Opción A | Opción B |
| :---: | :---: |
| ![Grid A](/preguntas/simce_mat_6b_e3/p27_grid_a.png) | ![Grid B](/preguntas/simce_mat_6b_e3/p27_grid_b.png) |
| **Opción C** | **Opción D** |
| ![Grid C](/preguntas/simce_mat_6b_e3/p27_grid_c.png) | ![Grid D](/preguntas/simce_mat_6b_e3/p27_grid_d.png) |',
  '[{"letra": "A", "texto": "Cuadrícula A", "es_correcta": true}, {"letra": "B", "texto": "Cuadrícula B", "es_correcta": false}, {"letra": "C", "texto": "Cuadrícula C", "es_correcta": false}, {"letra": "D", "texto": "Cuadrícula D", "es_correcta": false}]'::jsonb,
  'A',
  'En la opción A los dos catetos coinciden con las líneas perpendiculares de la cuadrícula, formando un ángulo recto exacto de 90°.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-28',
  'eval-simce-mat-6b-e3',
  28,
  'asig-1',
  'eje-mat-3',
  'hab-mat-2',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  '¿En cuál de las siguientes imágenes la **Figura 1** es **congruente** con la **Figura 2**?

| Opción A | Opción B |
| :---: | :---: |
| ![Congruencia A](/preguntas/simce_mat_6b_e3/p28_cong_a.png) | ![Congruencia B](/preguntas/simce_mat_6b_e3/p28_cong_b.png) |
| **Opción C** | **Opción D** |
| ![Congruencia C](/preguntas/simce_mat_6b_e3/p28_cong_c.png) | ![Congruencia D](/preguntas/simce_mat_6b_e3/p28_cong_d.png) |',
  '[{"letra": "A", "texto": "Imagen A", "es_correcta": false}, {"letra": "B", "texto": "Imagen B", "es_correcta": true}, {"letra": "C", "texto": "Imagen C", "es_correcta": false}, {"letra": "D", "texto": "Imagen D", "es_correcta": false}]'::jsonb,
  'B',
  'Dos figuras son congruentes si mantienen exactamente la misma forma y las mismas dimensiones de sus lados y ángulos (isometría).',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-29',
  'eval-simce-mat-6b-e3',
  29,
  'asig-1',
  'eje-mat-3',
  'hab-mat-3',
  'seleccion_multiple',
  '6° Básico',
  'alta',
  NULL,
  '¿Cuál de las siguientes afirmaciones sobre la congruencia de triángulos es **siempre verdadera**?',
  '[{"letra": "A", "texto": "Dos triángulos son congruentes si tienen la misma área.", "es_correcta": false}, {"letra": "B", "texto": "Dos triángulos son congruentes si tienen dos ángulos iguales.", "es_correcta": false}, {"letra": "C", "texto": "Dos triángulos equiláteros son congruentes si tienen el mismo perímetro.", "es_correcta": true}, {"letra": "D", "texto": "Dos triángulos son congruentes si sus tres ángulos interiores son respectivamente iguales.", "es_correcta": false}]'::jsonb,
  'C',
  'En un triángulo equilátero los 3 lados son iguales ($P = 3l$). Si tienen el mismo perímetro, sus lados miden exactamente lo mismo, cumpliendo el criterio LLL de congruencia.',
  3,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-30',
  'eval-simce-mat-6b-e3',
  30,
  'asig-1',
  'eje-mat-4',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  NULL,
  'Un atleta trota diariamente **3,5 km**. ¿Cuántos metros trota diariamente?',
  '[{"letra": "A", "texto": "35 m", "es_correcta": false}, {"letra": "B", "texto": "350 m", "es_correcta": false}, {"letra": "C", "texto": "3 500 m", "es_correcta": true}, {"letra": "D", "texto": "35 000 m", "es_correcta": false}]'::jsonb,
  'C',
  'Como 1 km equivale a 1 000 metros: 3,5 × 1 000 = 3 500 metros.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-31',
  'eval-simce-mat-6b-e3',
  31,
  'asig-1',
  'eje-mat-4',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  '/preguntas/simce_mat_6b_e3/p31_area_rectangulo.png',
  'El siguiente polígono es un rectángulo:

¿Cuánto mide el área de la parte sombreada?',
  '[{"letra": "A", "texto": "21 cm²", "es_correcta": false}, {"letra": "B", "texto": "42 cm²", "es_correcta": false}, {"letra": "C", "texto": "54 cm²", "es_correcta": true}, {"letra": "D", "texto": "108 cm²", "es_correcta": false}]'::jsonb,
  'C',
  'El área total del rectángulo es base × altura = 18 cm × 6 cm = 108 cm². La región sombreada corresponde a la mitad del rectángulo: 108 / 2 = 54 cm².',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-32',
  'eval-simce-mat-6b-e3',
  32,
  'asig-1',
  'eje-mat-5',
  'hab-mat-1',
  'seleccion_multiple',
  '6° Básico',
  'media',
  NULL,
  'Juan lanzó una moneda al aire 100 veces y obtuvo los siguientes resultados:

- **45 veces** salió cara.
- **55 veces** salió sello.

Si Juan repite el experimento y lanza la moneda otras 100 veces, ¿cuál es la tendencia más probable para los resultados?',
  '[{"letra": "A", "texto": "Saldrán más veces cara que sello.", "es_correcta": false}, {"letra": "B", "texto": "Saldrán más veces sello que cara.", "es_correcta": false}, {"letra": "C", "texto": "Saldrán exactamente 50 veces cara y 50 veces sello.", "es_correcta": false}, {"letra": "D", "texto": "Saldrán aproximadamente 50 veces cara y 50 veces sello.", "es_correcta": true}]'::jsonb,
  'D',
  'Dado que la probabilidad teórica de cara o sello en una moneda no cargada es 50%, la ley de los grandes números indica que el resultado tenderá aproximadamente a 50 caras y 50 sellos.',
  2,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-33',
  'eval-simce-mat-6b-e3',
  33,
  'asig-1',
  'eje-mat-5',
  'hab-mat-2',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  '/preguntas/simce_mat_6b_e3/p33_tallo_hojas.jpeg',
  'El siguiente diagrama de tallo y hojas muestra la cantidad de páginas leídas de un libro por un grupo de personas durante una semana:

¿Qué cantidad de páginas fue la máxima leída?',
  '[{"letra": "A", "texto": "14", "es_correcta": false}, {"letra": "B", "texto": "55", "es_correcta": false}, {"letra": "C", "texto": "65", "es_correcta": true}, {"letra": "D", "texto": "525", "es_correcta": false}]'::jsonb,
  'C',
  'En el diagrama de tallo y hojas, el valor mayor se obtiene combinando el tallo más alto (6) con la hoja mayor en esa fila (5), formando el valor 65 páginas.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-34',
  'eval-simce-mat-6b-e3',
  34,
  'asig-1',
  'eje-mat-5',
  'hab-mat-3',
  'seleccion_multiple',
  '6° Básico',
  'alta',
  NULL,
  'El promedio de las **4 calificaciones** de Diego en Matemática es exactamente **5,8**. Con esta información, ¿cuál de las siguientes afirmaciones es **siempre verdadera**?',
  '[{"letra": "A", "texto": "Diego obtuvo al menos una calificación igual a 5,8.", "es_correcta": false}, {"letra": "B", "texto": "La calificación más alta de Diego es mayor que 5,8.", "es_correcta": false}, {"letra": "C", "texto": "La suma de las 4 calificaciones de Diego es igual a 23,2.", "es_correcta": true}, {"letra": "D", "texto": "El valor 5,8 se encuentra en el centro de las notas ordenadas de menor a mayor.", "es_correcta": false}]'::jsonb,
  'C',
  'Por definición de promedio aritmético: Promedio = Suma / 4 = 5,8. Multiplicando ambos lados por 4: Suma = 5,8 × 4 = 23,2.',
  3,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

INSERT INTO public.preguntas (
  id,
  evaluacion_id,
  numero,
  asignatura_id,
  eje_tematico_id,
  habilidad_id,
  tipo,
  nivel,
  dificultad,
  imagen_url,
  enunciado,
  alternativas,
  respuesta_correcta,
  explicacion,
  puntaje,
  fuente,
  propietario_id
) VALUES (
  'preg-mat6b-e3-35',
  'eval-simce-mat-6b-e3',
  35,
  'asig-1',
  'eje-mat-5',
  'hab-mat-2',
  'seleccion_multiple',
  '6° Básico',
  'baja',
  '/preguntas/simce_mat_6b_e3/p35_ruleta.png',
  'Observa la siguiente ruleta:

Si se hace girar la flecha, ¿dónde es más probable que esta se detenga?',
  '[{"letra": "A", "texto": "H", "es_correcta": false}, {"letra": "B", "texto": "M", "es_correcta": true}, {"letra": "C", "texto": "R", "es_correcta": false}, {"letra": "D", "texto": "T", "es_correcta": false}]'::jsonb,
  'B',
  'La letra M ocupa la mayor cantidad de sectores o mayor área superficial de la ruleta, teniendo la probabilidad más alta de salir.',
  1,
  'Ensayo 3 SIMCE Matemática 6° Básico',
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  evaluacion_id = EXCLUDED.evaluacion_id,
  numero = EXCLUDED.numero,
  asignatura_id = EXCLUDED.asignatura_id,
  eje_tematico_id = EXCLUDED.eje_tematico_id,
  habilidad_id = EXCLUDED.habilidad_id,
  tipo = EXCLUDED.tipo,
  nivel = EXCLUDED.nivel,
  dificultad = EXCLUDED.dificultad,
  imagen_url = EXCLUDED.imagen_url,
  enunciado = EXCLUDED.enunciado,
  alternativas = EXCLUDED.alternativas,
  respuesta_correcta = EXCLUDED.respuesta_correcta,
  explicacion = EXCLUDED.explicacion,
  puntaje = EXCLUDED.puntaje,
  fuente = EXCLUDED.fuente;

COMMIT;